# Generated by Django 4.1 on 2022-09-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.BigIntegerField(default=0)),
                ("barcode", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("imported", "imported")],
                        max_length=10,
                    ),
                ),
                ("imported_t", models.DateTimeField(auto_now_add=True)),
                ("url", models.CharField(max_length=150)),
                ("product_name", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=50)),
                ("categories", models.CharField(max_length=450)),
                ("packaging", models.CharField(max_length=450)),
                ("brands", models.CharField(max_length=450)),
                ("image_url", models.CharField(max_length=150)),
            ],
        ),
    ]
