# Generated by Django 4.1 on 2022-09-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="code",
            field=models.BigIntegerField(default=0),
        ),
    ]
