# Generated by Django 4.1 on 2022-09-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_food", "0002_alter_produto_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Produto",
            new_name="Product",
        ),
    ]
