# Generated by Django 4.1 on 2022-08-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_food", "0004_alter_produto_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="barcode",
            field=models.BigIntegerField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="code",
            field=models.IntegerField(),
        ),
    ]
