# Generated by Django 4.1 on 2022-08-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_food", "0005_alter_produto_barcode_alter_produto_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="barcode",
            field=models.BigIntegerField(unique=True),
        ),
    ]
