# Generated by Django 4.1 on 2022-08-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_food", "0006_alter_produto_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="barcode",
            field=models.BigIntegerField(max_length=35),
        ),
        migrations.AlterField(
            model_name="produto",
            name="code",
            field=models.BigIntegerField(max_length=25, unique=True),
        ),
    ]
