# Generated by Django 4.1 on 2022-08-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_food", "0007_alter_produto_barcode_alter_produto_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="barcode",
            field=models.CharField(max_length=35),
        ),
    ]
