# Generated by Django 4.1 on 2022-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_food_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(max_length=35),
        ),
    ]
